maktab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('organization/', include("organization.urls")),
    path('sales/', include("sales.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quote/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("list", views.QuoteList.as_view(), name="quotelist"),
    path("detail/<int:pk>", views.QuoteDetail.as_view(), name="quote-detail"),
    path("create/<int:pk>", views.create_quote, name="create-quote"),
    path("item-add/<int:qid>", views.add_item, name="add-item"),
    path("item-delete/<int:pk>",
         views.delete_quote_item, name="delete-item"),
    path("select-organ", views.SelectOrgan.as_view(), name="select-organ"),
    path("item-edit/<int:pk>", views.QuoteItemUpdate.as_view(), name="edit-item")
]

sales/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("send_email", views.email, name="email"),
    path("quotes/", include("quote.urls")),
    path("show-followup", views.show_followup, name="showfollowup"),
    path("create-followup", views.create_followup, name="create-followup"),
    path("form-followup", views.FollowupFormView.as_view(), name="followup-form")
]

sales/models.py
from organization.models import Organization
from django.db import models
from django.utils.translation import ugettext as _
from django.contrib.auth import get_user_model
from . import enums

User = get_user_model()


class FollowUp(models.Model):
    """
    model that represent the sale follow up
    """
    report = models.TextField(verbose_name=_("sale report"))
    organization = models.ForeignKey(
        Organization, verbose_name=_("organization"), on_delete=models.PROTECT)
    creator = models.ForeignKey(User, verbose_name=_(
        "written by"), on_delete=models.PROTECT)
    written_on = models.DateTimeField(
        verbose_name=_("written at"), auto_now_add=True)


class EmailHistory(models.Model):
    reciver = models.ForeignKey(Organization, verbose_name=_(
        "to"), on_delete=models.PROTECT)
    status = models.CharField(
        max_length=20,
        verbose_name=_("status"),
        choices=enums.EmailStatus.choices,
        default=enums.EmailStatus.FAILED,
    )
    sender = models.ForeignKey(User, verbose_name=_(
        "from"), on_delete=models.PROTECT)
    send_on = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Send at"))

    def __str__(self):
        return f"{self.sender.username} to {self.reciver.name}"

sales/forms.py
from django import forms
from . import models


class FollowUpForm(forms.ModelForm):
    class Meta:
        model = models.FollowUp
        exclude = ['organization', 'creator']

sales/views.py
import json
from django.core.exceptions import PermissionDenied
from django.http.response import JsonResponse
from sales.tasks import send_email_task
from django.shortcuts import render, redirect
from .models import FollowUp
from django.contrib.auth import decorators
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from .tasks import send_email_task
from organization import models
from django.contrib import messages
from sales import forms
from django.views import generic
from django.contrib.auth import mixins

# Create your views here.


@decorators.login_required
@csrf_exempt
def email(request):  # send email to company
    qid = request.GET.get('qid')
    send_email_task.delay(request.user.pk, qid)
    return redirect('quotelist')


class FollowupFormView(mixins.LoginRequiredMixin, generic.TemplateView):
    """
    show the followup form 
    """
    extra_context = {"form": forms.FollowUpForm()}
    template_name = "sales/followup_form.html"

    def get(self, *args, **kwargs):
        orgid = self.request.GET.get("organ")
        self.extra_context.update({"orgid": orgid})
        return super().get(self.request, *args, **kwargs)


@decorators.login_required
def show_followup(request):
    orgid = request.GET.get("orgid")
    organ = models.Organization.objects.get(pk=orgid)
    if organ.creator != request.user:
        return JsonResponse(
            data={
                "success": False,
            },
            status=403,
        )
    qs = FollowUp.objects.filter(
        organization=organ, creator=request.user).order_by("-written_on")
    followups = list(qs.values('creator__username',
                     'written_on__date', 'written_on__time', 'report'))
    return JsonResponse({"result": followups})


@ decorators.login_required
@ require_POST
@ csrf_exempt
def create_followup(request):
    organization = models.Organization.objects.get(
        pk=request.POST.get("organization"))
    if organization.creator != request.user:
        return JsonResponse(
            data={
                "success": False,
            },
            status=403,
        )
    form = forms.FollowUpForm(data=request.POST)
    if form.is_valid():
        form.save(commit=False).creator = request.user
        form.save(commit=False).organization = organization
        form.save()
        return JsonResponse(
            data={
                "success": True,
                "message": "follow up created "
            },
            status=201,
        )
    else:
        return JsonResponse(
            data={
                "success": False,
            },
            status=400,
        )

sales/templates/sales/email.html
{% load static %}
{% load i18n %}
{% load math %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
        #quote {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
        }

        #quote td, #customers th {
        border: 1px solid #ddd;
        padding: 8px;
        }

        #quote tr:nth-child(even){background-color: #f2f2f2;}

        #quote tr:hover {background-color: #ddd;}

        #quote th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #04AA6D;
        color: white;
        }
</style>
</head>
<body >
<dl>
    <dt >{% trans "client" %}:</dt>
    <dd >{{ object.organization.name}}</dd>
   <!-- <dt class="col-sm-3">{% trans "date" %}</dt>
    <dd class="col-sm-9">{{ object.created_on.date }} {{ object.created_on.time }}</dd> -->
</dl>
<table id="quote">
        <thead>
        <tr>
            <th>#</th>
            <th>{% trans "product" %}</th>
            <th>{% trans "Qty" %}</th>
            <th>{% trans "Fee" %}</th>
            <th>{% trans "total price (tax included)" %}</th>
            <th>{% trans "Discount" %}</th>
            <th>{% trans "Ultimate Price" %}</th>

        </tr>
        </thead>
        {% for item in object.quoteitem_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.product.name}}</td>
                <td>{{ item.qty }}</td>
                <td>{{ item.product.price }} $</td>
                <td>{{ item.price }} $</td>
                <td>{{ item.discount }} $</td>
                <td>{{ item.price|sub:item.discount}} $</td>
            </tr>
        {% endfor %}
 <tfoot>
    <tr>
        <td colspan="3">
           {% trans "You save " %} : {{object.get_total_discount}} $
        </td>
        <td colspan="2">
            {% trans "price" %} : {{object.get_total_price}} $
        </td>
        <td colspan="2">
            {% trans "You will pay" %} : {{object.get_total_price|sub:object.get_total_discount}} $
        </td>
    </tr>
    </tfoot>        
</table>
</body>
</html>

sales/templates/sales/followup_form.html
{% extends 'users/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}Follow Up Form{% endblock title %}
{% block body %}
<h1 class='display-4' style='text-align:center'> {% trans "Follow up" %}</h1>
 <form method="post" enctype="multipart/form-data" id ="report">
            {% csrf_token %}
            {{ form|crispy}}
</form>
<button type="submit" class='btn btn-primary float-center' onclick="create_followup({{orgid}})">{% trans "add" %}</button>
{% block scripts %}
{% endblock scripts %}
<script>
function create_followup(orgid){
        var organization = orgid; 
        var report = $("#id_report").val();
        ajax_config = {
            url:"{% url 'create-followup' %}",
            method: "post",
            data: {
                organization:organization,
                report:report
            },
            success: function (response) {
                    document.getElementById("report").reset();
                    alert("Saved");
                    window.location.href = "../organization/detail/"+orgid
                },
            error: function (response) {
                    alert("your follow up didnt saved try again");
                }
        };
        $.ajax(ajax_config);
    }
</script>
{% endblock %}